/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package explorador_imagenes;

import java.awt.Image;
import java.io.File;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Joel
 */
public class ExploradorImagenes extends javax.swing.JFrame {

    FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagenes", "jpg", "png");

   
    
     
    

    public ExploradorImagenes() {
        initComponents();
        filechooser.setAcceptAllFileFilterUsed(false);
        filechooser.setControlButtonsAreShown(false);
        filechooser.addChoosableFileFilter (filtro);
        filechooser.setCurrentDirectory(new File("C:\\Users\\Joel\\Pictures"));
        
        ButtonGroup grupo1 = new ButtonGroup();
        grupo1.add(rbtnArea);
        grupo1.add(rbtnFast);
        grupo1.add(rbtnReplicate);
        grupo1.add(rbtnSmooth);
        
    }
     int resultado;
     
 private void muestraImagen(){
        ImageIcon icono1 = new  ImageIcon(filechooser.getSelectedFile().getPath());  
        Image img = icono1.getImage();         
         
        ImageIcon iconoEscalado = new ImageIcon(img.getScaledInstance(lblimagen.getWidth(),
                    lblimagen.getHeight(), resultado));

        lblimagen.setIcon(iconoEscalado);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filechooser = new javax.swing.JFileChooser();
        lblimagen = new javax.swing.JLabel();
        rbtnSmooth = new javax.swing.JRadioButton();
        rbtnFast = new javax.swing.JRadioButton();
        rbtnArea = new javax.swing.JRadioButton();
        rbtnReplicate = new javax.swing.JRadioButton();
        btnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        filechooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                filechooserPropertyChange(evt);
            }
        });

        lblimagen.setText("jLabel1");

        rbtnSmooth.setText("Scale_Smooth");
        rbtnSmooth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSmoothActionPerformed(evt);
            }
        });

        rbtnFast.setText("Scale_Fast");
        rbtnFast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFastActionPerformed(evt);
            }
        });

        rbtnArea.setText("Scale_area");
        rbtnArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAreaActionPerformed(evt);
            }
        });

        rbtnReplicate.setText("Scale_replicate");
        rbtnReplicate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnReplicateActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostrar Imagen");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtnFast)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnReplicate))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtnSmooth)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnArea)))
                        .addGap(58, 58, 58)
                        .addComponent(btnMostrar)))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filechooser, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnSmooth)
                            .addComponent(rbtnArea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnFast)
                            .addComponent(rbtnReplicate)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnMostrar)))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filechooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_filechooserPropertyChange
        if (filechooser.getSelectedFile()!=null) 
            muestraImagen();
    }//GEN-LAST:event_filechooserPropertyChange

    private void rbtnSmoothActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSmoothActionPerformed
    resultado = Image.SCALE_SMOOTH;        
    }//GEN-LAST:event_rbtnSmoothActionPerformed

    private void rbtnFastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFastActionPerformed
    resultado = Image.SCALE_FAST;       
    }//GEN-LAST:event_rbtnFastActionPerformed

    private void rbtnAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAreaActionPerformed
    resultado = Image.SCALE_AREA_AVERAGING;
    }//GEN-LAST:event_rbtnAreaActionPerformed

    private void rbtnReplicateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnReplicateActionPerformed
    resultado = Image.SCALE_REPLICATE;
    }//GEN-LAST:event_rbtnReplicateActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        muestraImagen();
    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExploradorImagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExploradorImagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExploradorImagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExploradorImagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExploradorImagenes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.JFileChooser filechooser;
    private javax.swing.JLabel lblimagen;
    private javax.swing.JRadioButton rbtnArea;
    private javax.swing.JRadioButton rbtnFast;
    private javax.swing.JRadioButton rbtnReplicate;
    private javax.swing.JRadioButton rbtnSmooth;
    // End of variables declaration//GEN-END:variables
}
