/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package explorador_ficheros;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Joel
 */
public class Explorador extends javax.swing.JFrame {

//objeto para filtrar tipos de archivo
    private FileNameExtensionFilter filtro1 = new FileNameExtensionFilter("Adobe", "pdf");
    private FileNameExtensionFilter filtro2 = new FileNameExtensionFilter("Word", "docx");
    private FileNameExtensionFilter filtro3 = new FileNameExtensionFilter("Java", "java", "class");
    private FileNameExtensionFilter filtro4 = new FileNameExtensionFilter("Imagen", "png", "jpg");
// variables para saber que se selecciona.
    int seleccionado;
    int seleccionado2;

    /**
     * Creates new form Explorador
     */
    public Explorador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBorrar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnCopiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnCopiar.setText("Copiar");
        btnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCopiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnBorrar)
                .addGap(44, 44, 44)
                .addComponent(btnCrear)
                .addGap(45, 45, 45)
                .addComponent(btnCopiar)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed

        JFileChooser borrar = new JFileChooser("System.getProperty(“user.dir”);");
        borrar.setDialogTitle("Selección de archivos");
        borrar.setFileFilter(filtro1);
        borrar.setFileFilter(filtro2);
        borrar.setFileFilter(filtro3);
        borrar.setFileFilter(filtro4);
        seleccionado = borrar.showDialog(null, "Borrar");

        if (seleccionado == JFileChooser.APPROVE_OPTION) {

            int siono = JOptionPane.showConfirmDialog(null, "¿Desea borrar el archivo?", "", JOptionPane.YES_NO_OPTION);

            if (siono == JOptionPane.YES_OPTION) {
                File fichero = borrar.getSelectedFile();
                fichero.delete();

            } else {
                System.out.println("Adios");
            }

        } else {
            System.out.println("Adios");
        }

    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        File fichero = new File("System.getProperty(“user.dir”);");
        try {
            if (fichero.createNewFile()) {
                System.out.println("Se creó un fichero vacio");
            } else {
                System.out.println("Ya se creó el fichero");
            }
        } catch (IOException ioe) {
            ioe.printStackTrace();
        }


    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarActionPerformed
        JFileChooser copiar = new JFileChooser("System.getProperty(“user.dir”);");

        copiar.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        JFileChooser copiar2 = new JFileChooser("C:\\Users\\Joel\\Documents\\carpetaPruebas");
        copiar2.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        copiar2.setDialogTitle("Elegir destino");

        copiar.setDialogTitle("Selección de archivos");
        copiar.setFileFilter(filtro1);
        copiar.setFileFilter(filtro2);
        copiar.setFileFilter(filtro3);
        copiar.setFileFilter(filtro4);
        seleccionado = copiar.showDialog(null, "copiar a...");

        if (seleccionado == JFileChooser.APPROVE_OPTION) {
            File archivoacopiar = copiar.getSelectedFile();
            String rutaOrig = archivoacopiar.getPath();
            Path origen = Paths.get(rutaOrig);

            seleccionado2 = copiar2.showDialog(null, "copiar");

            if (seleccionado2 == JFileChooser.APPROVE_OPTION) {
                
                File archivoCopiado = copiar2.getSelectedFile();
                
                String rutaDestino = archivoCopiado.getPath();
                
                Path destino = Paths.get(rutaDestino);
                try {
                    Files.copy(origen, destino, REPLACE_EXISTING);
                    System.out.println("Se copió correctamente");
                } catch (IOException ex) {
                    Logger.getLogger(Explorador.class.getName()).log(Level.SEVERE, null, ex);
                }

            }else {
                System.out.println("No se pudo copiar el archivo");
            }
        }


    }//GEN-LAST:event_btnCopiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Explorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Explorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Explorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Explorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Explorador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCopiar;
    private javax.swing.JButton btnCrear;
    // End of variables declaration//GEN-END:variables
}
